### ISSUE TITLE
Don't work with python 3.12

### ISSUE THREAD

**Issue by axel584** [buruzaemon/natto-py#129]
Hi,
When I use the lib natto with python 3.12, i've got this error : 

```
  File "/home/axel/Documents/code/lute-v3/lute/parse/mecab_parser.py", line 18, in <module>
    from natto import MeCab
  File "/home/axel/.local/lib/python3.12/site-packages/natto/__init__.py", line 1, in <module>
    from cgi import escape
ImportError: cannot import name 'escape' from 'cgi' (/usr/lib/python3.12/cgi.py)
```

Do you plan to upgrade the lib to work with python 3.12 ?
Thank you,

Axel

**Comment by buruzaemon** [comment]
Hello, @axel584, and thank you for reaching out to me.

I do not have any current plans to upgrade natto-py to support Python beyond 3.10, but only because I do not have much free time nowadays. You are welcome, of course, to fork natto-py and investigate how to bring support for Python > 3.10.

However, I am curious about the stack trace you present. If possible, could you please provide me with a requirements.txt or environment.yml for your case, and a short but clear description of how to reproduce this error you have observed?
